spring:
  application:
    name: Authent API

  datasource:
    url: jdbc:postgresql://localhost:5432/authentapi
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:codeur47}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true